name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab01
      - name: Test with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: test
          build-root-directory: ./Lab01
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: compiled-artifact
          path: ./Lab01/build/libs/*.jar
  build2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab02
      - name: Test with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: test
          build-root-directory: ./Lab02
  build3:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: build
          build-root-directory: ./Lab03
      - name: Test with Gradle
        uses: gradle/gradle-build-action@main
        with:
          arguments: test
          build-root-directory: ./Lab03
