name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: ./Lab01
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-artifact1
          path: ./Lab01/build/libs/*.jar
